<?php
require('fpdf.php');
session_start();
class PDF extends FPDF
{        
    // Page header
function Header()
{
    // Logo
   // $this->Image('logo.png',10,6,30);
    // Arial bold 15
    
    $this->Image('certificate.png',0,0,300);
    // $this->Image('Sunset.jpg',0,0,10,300);
    // $this->Image('Sunset.jpg',200,0,10,300);
    // $this->Image('Sunset.jpg',10,0,190,10);
    // $this->Image('Sunset.jpg',10,287,190,10);
    $this->SetFont('Arial','B',46);
    // Move to the right
    $this->Cell(50);
    // Title
    //$this->Cell(110,70,''.$username,'');//old value 20
    // Line break
    $this->Ln(30);
}

// Page footer
function Footer()
{
    // Position at 1.5 cm from bottom
    $this->SetY(-15);
    // Arial italic 8
    $this->SetFont('Arial','I',8);
    // Page number
   // $this->Cell(0,10,'Page '.$this->PageNo().'/{nb}',0,0,'C');
//    $this->Cell(1,25,'Certificate Generated By Quiz Heads');
//    $this->SetY(-15);
//    $this->SetX(180);
//    $this->Cell(1,25,'*Valid For 1 year');
   
//    $this->SetY(-15);
//    $this->SetX(90);
//    $this->Cell(1,25,'© all copyrights reserved');
   
}
}

// Instanciation of inherited class
$pdf = new PDF();
$pdf->AliasNbPages();
$pdf->AddPage('L');
$pdf->SetFont('Times','I',30);

//$pdf->Cell(110,70,echo $username,'');//old value 20}

//$a='sneha';
// for($i=1;$i<=10;$i++)
//     $pdf->Cell(0,10,'Printing line number '.$i,0,1);

// $pdf->Cell(40,10,);
$username = isset($_POST["hf_username"])? $_POST["hf_username"]:$_SESSION["uname"];
$quiz = isset($_POST["hf_quiz"])? $_POST["hf_quiz"]:$_SESSION["hf_quiz"];
$marks = isset($_POST["hf_marks"])? $_POST["hf_marks"]:$_SESSION["hf_marks"];
$pdf->Ln(30);
$pdf->SetFont('Times','I',30);
$pdf->Cell(150,70,$username,'',0,'R');
$pdf->Ln(20);
$pdf->SetFont('Times','I',25);
$pdf->Cell(199,75,$quiz,'',1,'R');
$pdf->Cell(167,-25,$marks,'',0,'R');
// $pdf->SetMargins(0.5, 0.5, 0.5);

// $pdf->Cell(1);
//$pdf->SetTextcolor(0,153,153);

 $pdf->Output();

// require('fpdf.php');
// $a = 10;
// $pdf = new FPDF();
// $pdf->AddPage();
// $pdf->SetFont('Arial','B',16);
// $pdf->Cell(40,10,'Hello World!'.$a);
// $pdf->Output();
